name: lzma
version: 1.0.0
homepage: https://github.com/jcmellado/dart-lzma
description: LZMA compression library.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  
dev_dependencies:
  test: ^1.16.7
